from unit import _core

from enum import Enum

class OpCode(Enum):
    LOAD_STRING = _core.UNIT_OP_LOAD_STRING
    LOAD_INTEGER = _core.UNIT_OP_LOAD_INTEGER
    LOAD_LOCAL = _core.UNIT_OP_LOAD_LOCAL
    STORE_LOCAL = _core.UNIT_OP_STORE_LOCAL
    ADD = _core.UNIT_OP_ADD
    SUBTRACT = _core.UNIT_OP_SUBTRACT
    MULTIPLY = _core.UNIT_OP_MULTIPLY
    DIVIDE = _core.UNIT_OP_DIVIDE
    MODULO = _core.UNIT_OP_MODULO
    JUMP_TO = _core.UNIT_OP_JUMP_TO
    JUMP_IF_FALSE = _core.UNIT_OP_JUMP_IF_FALSE
    JUMP_IF_TRUE = _core.UNIT_OP_JUMP_IF_TRUE
    EXIT = _core.UNIT_OP_EXIT
    RETURN_VALUE = _core.UNIT_OP_RETURN_VALUE
    LOAD_ARGUMENT = _core.UNIT_OP_LOAD_ARGUMENT
    PREPARE_CALL = _core.UNIT_OP_PREPARE_CALL
    CALL_NAME = _core.UNIT_OP_CALL_NAME
    CALL_PROCEDURE = _core.UNIT_OP_CALL_PROCEDURE
    COMPARE_EQUAL = _core.UNIT_OP_COMPARE_EQUAL
    COMPARE_NOT_EQUAL = _core.UNIT_OP_COMPARE_NOT_EQUAL
    COMPARE_GREATER = _core.UNIT_OP_COMPARE_GREATER
    COMPARE_GREATER_EQUAL = _core.UNIT_OP_COMPARE_GREATER_EQUAL
    COMPARE_LESS = _core.UNIT_OP_COMPARE_LESS
    COMPARE_LESS_EQUAL = _core.UNIT_OP_COMPARE_LESS_EQUAL
    COPY = _core.UNIT_OP_COPY
    SWAP = _core.UNIT_OP_SWAP
    POP = _core.UNIT_OP_POP
    ADDRESS_OF = _core.UNIT_OP_ADDRESS_OF
    READ_BYTES = _core.UNIT_OP_READ_BYTES
    WRITE_BYTES = _core.UNIT_OP_WRITE_BYTES
    CONVERT = _core.UNIT_OP_CONVERT
